### ISSUE TITLE
Missing definition of the HasPostgres instance in the example and the docu

### ISSUE THREAD

**Issue by bulldog98** [mightybyte/snaplet-postgresql-simple#23]
Hi,

right now I'm trying to port my old snap project to the new snaplet-postgres-simple release, but I get No instance nor default method for class operation Snap.Snaplet.PostgresqlSimple.Internal.setLocalPostgresState for my Type as soon as I try to load a page with an database query.

**Comment by dzhus** [comment]
@mightybyte, What do I write if I have a lens defined directly (to be able to use provide it from upper-level snaplet in initializer)?

```
data MySnaplet b = MS{db :: SnapletLens b Postgres}

instance HasPostgres (Handler b (MySnaplet b)) where
  setLocalPostgresState s = ???
```
