### ISSUE TITLE
How hard would be to switch from resource-pool-catchio to "standard" resource-pool?

### ISSUE THREAD

**Issue by adinapoli** [mightybyte/snaplet-postgresql-simple#25]
Hi Doug,

as the moment of writing this resource-pool-catchio depends from MonadCatchIO-transformers, which has been deprecated in favour of the exception package:

http://hackage.haskell.org/package/MonadCatchIO-transformers

Furthermore, it's not being updated since March 2012, whereas Bryan recently updated a new version of his original package.

I guess the only blocker is that we need explicit support for catching exceptions, right? 

Overall seems a shame to depend on a deprecated package.

Alfredo

**Comment by mightybyte** [comment]
This will happen when Snap 1.0 is released which uses monad-control instead of MonadCatchIO.

**Comment by adinapoli** [comment]
Good to know, thanks Doug.

A.
