### ISSUE TITLE
Make snaplet-postgresql-simple ==0.6.* work with base-4.8

### ISSUE THREAD

**Issue by robertmassaioli** [mightybyte/snaplet-postgresql-simple#26]
I'm currently getting the following build errors:

    base==4.8.0.0/installed-901..., snaplet-postgresql-simple => base>=4 && <4.8)

I can also see that version 0.5 did not have this issue. :( This is a shame and it would be good if we could increase the bounds and release again.

**Comment by mightybyte** [comment]
Fixed

**Comment by ajknoll** [comment]
This was regressed in 0.6.0.2, would it be possible to reopen this please?

**Comment by robertmassaioli** [comment]
I can confirm that this seems to have regressed.

**Comment by mightybyte** [comment]
Sorry about that.  It looks like I updated the bounds on hackage, but forgot to also make the change in git.  It's fixed now.
