### ISSUE TITLE
Do not create snaplets/postgresql-simple/devel.cfg

### ISSUE THREAD

**Issue by int-index** [mightybyte/snaplet-postgresql-simple#27]
When using `pgsInit'` (with manual configuration), I don't want the `snaplets/postgresql-simple/devel.cfg` file to be created. Especially since it contains incorrect (default) configuration, and not the one I specified.

**Comment by mightybyte** [comment]
What is incorrect about the default one?  If you don't want it to be created, then just create an empty snaplets/postgresql-simple directory.

**Comment by int-index** [comment]
> What is incorrect about the default one?

The fact that it's default and not the one I give to `pgsInit'` - that's not the behavior I would expect. Because if there's a configuration file, the application should behave as specified in it.

> If you don't want it to be created, then just create an empty snaplets/postgresql-simple directory
Didn't know that, it's certainly better than creating a config file that doesn't match the application behavior. But I'd prefer to have control over what directories are created by my application: if I'm not using the config file - why have it?

**Comment by mightybyte** [comment]
Yep, I'm with you.  I was thinking that I couldn't control it from this package.  But I can.  It's fixed now.
