### ISSUE TITLE
errors-2.0?

### ISSUE THREAD

**Issue by gibiansky** [mightybyte/snaplet-postgresql-simple#35]
Could this be updated to work with errors-2.0? This would make it easy to work with latest Stackage and this package.

**Comment by mightybyte** [comment]
I dropped the errors dependency and released a new version to hackage.  But as a side note, if you encounter similar problems in the future you might consider not using stackage as it unnecessarily restricts what versions you can work with.

**Comment by gibiansky** [comment]
You can actually use Stackage with older versions, it's just more of a
hassle. Thanks!

**Comment by mightybyte** [comment]
Yes, it's more of a hassle because precisely because the restrictions were unnecessary.  :)
