### ISSUE TITLE
Use exceptions instead of MonadCatchIO-transformers

### ISSUE THREAD

**Issue by ajnsit** [mightybyte/snaplet-postgresql-simple#38]
As the title says. `MonadCatchIO-transformers` is deprecated in favor of the `exceptions` package.

I opened a similar issue for snap itself here - https://github.com/snapframework/snap/issues/169

**Comment by mightybyte** [comment]
Like snap, this package has switched to using monad-control in the 1.0 branch.

https://github.com/mightybyte/snaplet-postgresql-simple/blob/1.0/snaplet-postgresql-simple.cabal#L48
