### ISSUE TITLE
Update 'base' version bound to include 4.9

### ISSUE THREAD

**Issue by robertmassaioli** [mightybyte/snaplet-postgresql-simple#39]
Hi, I'm getting the following error in my build against GHC latest:

    next goal: snaplet-postgresql-simple (dependency of hackathon-0.36)
    rejecting: snaplet-postgresql-simple-0.6.0.4, 0.6.0.3, 0.6.0.2, 0.6.0.1
    (conflict: base==4.9.0.0/installed-4.9..., snaplet-postgresql-simple =>
    base>=4 && <4.9)

0.6.0.4 seems to be the latest version. Can you bump it to include the latest GHC?

**Comment by mightybyte** [comment]
Snap doesn't support GHC 8 yet.  There is still [a little more work to be done for that](https://github.com/snapframework/snap/wiki/1.0-TODO-List).  We're planning to release it in two weeks on August 7.

**Comment by zoran119** [comment]
@mightybyte, any plans for the release you mentioned above?

**Comment by mightybyte** [comment]
@zoran119 Just released it.
