### ISSUE TITLE
Overlapping instances for HasPostgres ReaderT

### ISSUE THREAD

**Issue by sopvop** [mightybyte/snaplet-postgresql-simple#42]
These two instances seem to overlap [one](https://github.com/mightybyte/snaplet-postgresql-simple/blob/master/src/Snap/Snaplet/PostgresqlSimple.hs#L182) and [two](https://github.com/mightybyte/snaplet-postgresql-simple/blob/master/src/Snap/Snaplet/PostgresqlSimple/Internal.hs#L62).

At least ghc 8.0.1 doesn't want to compile my `ReaderT Postgres IO a` usage

I haven't checked yet if OVERLAPPING/OVERLAPPABLE fixes it.
Also, do you need to support 7.8 with old OverlappableInstances syntax?

**Comment by mrkkrp** [comment]
So, is there a new release with this fix?
