### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by mjhoy** [mightybyte/snaplet-postgresql-simple#48]
The current version on Hackage fails for GHC 8.2, looks like that's been fixed in master since November though.

**Comment by robertmassaioli** [comment]
It would be great to get a release of this out the door. Ping @mightybyte 

It's now affecting my ability to upgrade too.

Cheers!

**Comment by mightybyte** [comment]
Hmmm, I was hoping I could sneak 8.4 support in at the same time since this is a major version bump.

**Comment by menelaos** [comment]
Yes, please sneak it in! :innocent: :heart:

**Comment by mightybyte** [comment]
Thanks for the continued reminders.  At the moment this is blocked on 8.4 support for some dependencies.  I'm working through some of them and hopefully the community is working through others that I haven't encountered yet.  It always takes some time for new GHC support to percolate through the ecosystem.

**Comment by mightybyte** [comment]
Status update: still waiting on postgresql-simple support for 8.4.

**Comment by menelaos** [comment]
Thanks for the update! A non-maintainer upload for `postgresql-simple` was requested [here](https://github.com/haskell-infra/hackage-trustees/issues/155), but that will take at least two weeks to go through.

**Comment by mightybyte** [comment]
New version released as 1.1.0.0.

**Comment by menelaos** [comment]
Thanks a lot!
