### ISSUE TITLE
colDef missing userRole & userMeta

### ISSUE THREAD

**Issue by jazzyeagle** [mightybyte/snaplet-postgresql-simple#50]
I want to use userMeta to store data about my users in lieu of creating a separate table.  When looking in my db table, though, I noticed that both the userRoles & userMeta fields were missing from the table.  Taking a look in your source code, it appears that they the CreateTableIfMissing function iterates over the colDef array, which is missing these two fields.

I'm not sure if this was intentional or a simple miss.  If intentional, does the author have a preference as to how these items should be handled, so that I know how to resolve the issue?  If unintentional, can you please update the lib accordingly?  If you need me to send an MR, let me know.

Thanks!

**Comment by mightybyte** [comment]
The roles and meta fields have been in there from the beginning but never got implemented.  I abandoned the roles idea, so I don't think we should put that one in.  The meta idea I always worked around by using my own separate table for app-specific user data.  That approach has some advantages and is probably what I would recommend.  But if you want to send a PR wiring up the meta column, I'm open to that.

**Comment by jazzyeagle** [comment]
Thank you for the response.  I personally see the advantages the other way:  the AuthUser type is already readily available and has the fields available, which means I don't have to create the additional table with a Foreign Key, the additional query I'd have to write, which means there are two db transactions instead of just one.  I just assumed that the roles and meta values where there for the website programmer to implement directly.

That being said, I would love to hear how you see the advantages of the two table solution.  Perhaps you have reasons I haven't thought of that would sway me to your POV.  Thanks for entertaining the idea.

**Comment by mightybyte** [comment]
Yeah, I understand the advantages of having it in the same table.  But you're still limited in how much you can take advantage of the DB's power since all the extra data is bunched into a single column. 
 Also, some DB libraries don't work well with types coming from elsewhere.

**Comment by jazzyeagle** [comment]
Thank you for the response.  That does make sense.  I'll go ahead and follow your recommendation and close this issue.  Thank you for entertaining the idea!  I appreciate it!

**Comment by mightybyte** [comment]
The auth stuff in snaplet-postgresql-simple was intended to allow people to get off and running quickly with a decent number of out-of-the-box features.  I think it succeeded in that.  But on the other hand, we've also seen that real-world apps often end up needing a lot more customization than can be easily supplied in an out-of-the-box way.  So perhaps the path in this area is to start with the off the shelf auth, use that to get yourself going, then transition to your own thing--perhaps even by copy and pasting the code and then modifying it as needed.
